const fs=require('fs'),p=require('path');
const R='c:/Users/raima/OneDrive/Desktop/haikyu/frontend';
const W=(f,c)=>{fs.mkdirSync(p.dirname(p.join(R,f)),{recursive:true});fs.writeFileSync(p.join(R,f),c);console.log('wrote',f);};
W('src/pages/Live.jsx',[
"import { useEffect, useRef, useState } from 'react';","import { useNavigate } from 'react-router-dom';",
"import { Mic, MicOff, Send, SkipForward, Flag } from 'lucide-react';","import api from '../services/api.js';",
"export default function Live(){","const nav=useNavigate();",
"const[data,setData]=useState(()=>{try{return JSON.parse(sessionStorage.getItem('iq_live'));}catch{return null;}});",
"const[idx,setIdx]=useState(0);const[ans,setAns]=useState('');const[ev,setEv]=useState(null);const[busy,setBusy]=useState(false);",
"const[sec,setSec]=useState(0);const[listening,setListening]=useState(false);const rec=useRef(null);",
"useEffect(()=>{const t=setInterval(()=>setSec((s)=>s+1),1000);return()=>clearInterval(t);},[]);",
"useEffect(()=>{if(!data)nav('/app/setup');},[data]);",
"if(!data)return null;","const qs=data.questions;const q=qs[idx];",
"const mm=String(Math.floor(sec/60)).padStart(2,'0');const ss=String(sec%60).padStart(2,'0');",
"const total=Math.min(qs.length,data.interview.totalQuestions);",
"const toggleVoice=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;",
"if(!SR){alert('Voice mode is not supported by this browser. Please use text mode.');return;}",
"if(listening){rec.current&&rec.current.stop();setListening(false);return;}",
"const r=new SR();rec.current=r;r.lang='en-US';",
"r.onresult=(e)=>{setAns((a)=>(a?a+' ':'')+e.results[0][0].transcript);};",
"r.onend=()=>setListening(false);r.onerror=()=>setListening(false);r.start();setListening(true);};",
"const submit=async(skip)=>{if(!skip&&ans.trim().length<3){alert('Write a short answer first.');return;}",
"setBusy(true);try{const r=await api.post('/api/interviews/'+data.interview.id+'/answers',{questionId:q.id,questionText:q.questionText,answerText:skip?'(skipped)':ans,difficulty:q.difficulty});",
"setEv({...r.data,skipped:skip});}catch(e){alert(e.response?.data?.message||'Submit failed');}finally{setBusy(false);}};",
"const next=()=>{const nq=ev&&ev.nextQuestion&&ev.nextQuestion.id?ev.nextQuestion:null;",
"if(nq&&!qs.some((x)=>x.id===nq.id))qs.push(nq);setEv(null);setAns('');",
"if(idx+1>=total){finish();}else{setIdx(idx+1);}};",
"const finish=async()=>{try{await api.post('/api/interviews/'+data.interview.id+'/complete');nav('/app/report/'+data.interview.id);}catch(e){alert('Complete failed');}};",
"return(<div className='live-grid'>",
"<div className='glass pad'><div className='live-top'><span>Question {idx+1} of {total}</span><span className='mono'>{mm}:{ss}</span></div>",
"<div className='bar big'><i style={{width:(idx/Math.max(1,total))*100+'%'}}/></div>",
"<h2 className='q'>{q.questionText}</h2><div className='q-meta'><span className='chip on'>{q.category}</span><span className='chip on'>{q.difficulty}</span></div>",
"{!ev?(<><textarea rows='7' placeholder='Type your answer (4-6 sentences with an example)...' value={ans} onChange={(e)=>setAns(e.target.value)}/>",
"<div className='row'><button className='btn ghost' onClick={toggleVoice}>{listening?<MicOff size={17}/>:<Mic size={17}/>} {listening?'Stop':'Voice'}</button>",
"<button className='btn ghost' onClick={()=>submit(true)} disabled={busy}><SkipForward size={17}/> Skip</button>",
"<button className='btn primary' onClick={()=>submit(false)} disabled={busy}><Send size={17}/> {busy?'Evaluating...':'Submit'}</button>",
"<button className='btn ghost' onClick={finish}><Flag size={17}/> End</button></div></>)",
":(<div className='eval'><h3>AI Evaluation: {ev.evaluation.score}%</h3><p>{ev.evaluation.feedback}</p>",
"<div className='alert info'>Next: <b>{ev.nextDifficulty}</b> - {ev.adaptiveReason}</div>",
"<button className='btn primary lg' onClick={next}>Continue</button></div>)}",
"</div>",
"<aside className='glass pad coach'><h3>AI Interviewer</h3><p className='muted'>Take your time. Explain with an example.</p>",
"<div className='trend-row'><span>Difficulty</span><b>{q.difficulty}</b></div>",
"{ev&&<div className='trend-row'><span>Last score</span><b>{ev.evaluation.score}%</b></div>}",
"<div className='trend-row'><span>Progress</span><b>{idx+1}/{total}</b></div></aside>",
"</div>);}"
].join('\n'));
